Elcodi\Component\Product\Entity\Manufacturer:
    type: entity
    repositoryClass: Elcodi\Component\Product\Repository\ManufacturerRepository
    table: manufacturer
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            column: name
            type: string
            length: 255
            nullable: false
        slug:
            column: slug
            type: string
            length: 255
            nullable: false
        description:
            column: description
            type: text
            nullable: true
        metaTitle:
            column: meta_title
            type: string
            length: 255
            nullable: true
        metaDescription:
            column: meta_description
            type: string
            length: 255
            nullable: true
        metaKeywords:
            column: meta_keywords
            type: string
            length: 255
            nullable: true
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
        enabled:
            column: enabled
            type: boolean

    oneToMany:
        products:
            targetEntity: Elcodi\Component\Product\Entity\Interfaces\ProductInterface
            mappedBy: manufacturer

    lifecycleCallbacks:
        preUpdate: [loadUpdateAt]
        prePersist: [loadUpdateAt]
