parameters:

    #
    # Services
    #
    elcodi.core.product.service.product_manager.class: Elcodi\ProductBundle\Services\ProductManager
    elcodi.core.product.service.category_manager.class: Elcodi\ProductBundle\Services\CategoryManager
    elcodi.core.product.service.product_collection_provider.class: Elcodi\ProductBundle\Services\ProductCollectionProvider

    #
    # Form Types
    #
    elcodi.core.product.form_type.category.class: Elcodi\ProductBundle\Form\Type\CategoryType
    elcodi.core.product.form_type.manufacturer.class: Elcodi\ProductBundle\Form\Type\ManufacturerType
    elcodi.core.product.form_type.product.class: Elcodi\ProductBundle\Form\Type\ProductType

    #
    # Entities
    #
    elcodi.core.product.entity.product.class: Elcodi\ProductBundle\Entity\Product
    elcodi.core.product.entity.category.class: Elcodi\ProductBundle\Entity\Category
    elcodi.core.product.entity.manufacturer.class: Elcodi\ProductBundle\Entity\Manufacturer

    #
    # Factories
    #
    elcodi.core.product.factory.product.class: Elcodi\ProductBundle\Factory\ProductFactory
    elcodi.core.product.factory.manufacturer.class: Elcodi\ProductBundle\Factory\ManufacturerFactory
    elcodi.core.product.factory.category.class: Elcodi\ProductBundle\Factory\CategoryFactory
