parameters:

    #
    # Entities
    #
    elcodi.core.product.entity.product.class: Elcodi\ProductBundle\Entity\Product
    elcodi.core.product.entity.variant.class: Elcodi\ProductBundle\Entity\Variant
    elcodi.core.product.entity.category.class: Elcodi\ProductBundle\Entity\Category
    elcodi.core.product.entity.manufacturer.class: Elcodi\ProductBundle\Entity\Manufacturer

    #
    # Repositories
    #
    elcodi.core.product.repository.product.class: Elcodi\ProductBundle\Repository\ProductRepository
    elcodi.core.product.repository.variant.class: Elcodi\ProductBundle\Repository\VariantRepository
    elcodi.core.product.repository.category.class: Elcodi\ProductBundle\Repository\CategoryRepository
    elcodi.core.product.repository.manufacturer.class: Elcodi\ProductBundle\Repository\ManufacturerRepository

    #
    # Services
    #
    elcodi.core.product.service.category_manager.class: Elcodi\ProductBundle\Services\CategoryManager
    elcodi.core.product.service.product_collection_provider.class: Elcodi\ProductBundle\Services\ProductCollectionProvider

    #
    # Factories
    #
    elcodi.core.product.factory.abstract.abstract.class: Elcodi\ProductBundle\Factory\Abstracts\AbstractPurchasableFactory
    elcodi.core.product.factory.product.class: Elcodi\ProductBundle\Factory\ProductFactory
    elcodi.core.product.factory.variant.class: Elcodi\ProductBundle\Factory\VariantFactory
    elcodi.core.product.factory.manufacturer.class: Elcodi\ProductBundle\Factory\ManufacturerFactory
    elcodi.core.product.factory.category.class: Elcodi\ProductBundle\Factory\CategoryFactory

    #
    # Twig extensions
    #
    elcodi.core.product.twig_extension.product.class: Elcodi\ProductBundle\Twig\ProductExtension
