parameters:

    #
    # Services
    #
    elcodi.provider.category_tree.class: Elcodi\Component\Product\Services\CategoryTree
    elcodi.provider.product_collection.class: Elcodi\Component\Product\Services\ProductCollectionProvider

    #
    # Factories
    #
    elcodi.factory.product.class: Elcodi\Component\Product\Factory\ProductFactory
    elcodi.factory.product_variant.class: Elcodi\Component\Product\Factory\VariantFactory
    elcodi.factory.manufacturer.class: Elcodi\Component\Product\Factory\ManufacturerFactory
    elcodi.factory.category.class: Elcodi\Component\Product\Factory\CategoryFactory

    #
    # Twig extensions
    #
    elcodi.twig_extension.product.class: Elcodi\Component\Product\Twig\ProductExtension
