services:

    #
    # Event Listeners
    #
    elcodi.event_listener.product_category_integrity:
        class: Elcodi\Component\Product\EventListener\ProductCategoryIntegrityEventListener
        arguments:
            category_integrity_fixer: @elcodi.service.category_integrity_fixer
        tags:
            - { name: doctrine.event_listener, event: preFlush, method: preFlush }
            - { name: doctrine.event_listener, event: preUpdate, method: preUpdate }
