services:

    #
    # Factories
    #

    #
    # Factory for Product entities
    #
    elcodi.factory.product:
        class: %elcodi.factory.product.class%
        parent: elcodi.core.currency.factory.abstract.purchasable
        calls:
            - [setEntityNamespace, ["%elcodi.core.product.entity.product.class%"]]
            - [setUseStock, [@=elcodi_config('product.use_stock')]]

    #
    # Factory for Variant entities
    #
    elcodi.factory.product_variant:
        class: %elcodi.factory.product_variant.class%
        parent: elcodi.core.currency.factory.abstract.purchasable
        calls:
            - [setEntityNamespace, ["%elcodi.core.product.entity.product_variant.class%"]]

    #
    # Factory for Manufacturer entities
    #
    elcodi.factory.manufacturer:
        class: %elcodi.factory.manufacturer.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.product.entity.manufacturer.class%"]]

    #
    # Factory for Category entities
    #
    elcodi.factory.category:
        class: %elcodi.factory.category.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.product.entity.category.class%"]]
