services:

    #
    # Factories
    #

    #
    # Abstract purchasable factory
    #
    elcodi.core.product.factory.abstract.purchasable:
        class: %elcodi.core.product.factory.abstract.abstract.class%
        abstract: true
        arguments:
            currency_wrapper: @elcodi.currency_wrapper

    #
    # Factory for Product entities
    #
    elcodi.core.product.factory.product:
        class: %elcodi.core.product.factory.product.class%
        parent: elcodi.core.product.factory.abstract.purchasable
        calls:
            - [setEntityNamespace, ["%elcodi.core.product.entity.product.class%"]]

    elcodi.factory.product:
        alias: elcodi.core.product.factory.product

    #
    # Factory for Variant entities
    #
    elcodi.core.product.factory.variant:
        class: %elcodi.core.product.factory.variant.class%
        parent: elcodi.core.product.factory.abstract.purchasable
        calls:
            - [setEntityNamespace, ["%elcodi.core.product.entity.variant.class%"]]

    elcodi.factory.product_variant:
        alias: elcodi.core.product.factory.variant

    #
    # Factory for Manufacturer entities
    #
    elcodi.core.product.factory.manufacturer:
        class: %elcodi.core.product.factory.manufacturer.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.product.entity.manufacturer.class%"]]

    elcodi.factory.manufacturer:
        alias: elcodi.core.product.factory.manufacturer

    #
    # Factory for Category entities
    #
    elcodi.core.product.factory.category:
        class: %elcodi.core.product.factory.category.class%
        calls:
            - [setEntityNamespace, ["%elcodi.core.product.entity.category.class%"]]

    elcodi.factory.category:
        alias: elcodi.core.product.factory.category
