services:

    #
    # Factories
    #

    #
    # Factory for Product entities
    #
    elcodi.factory.product:
        class: %elcodi.factory.product.class%
        parent: elcodi.factory.abstract.purchasable
        calls:
            - [setEntityNamespace, ["%elcodi.entity.product.class%"]]
            - [setUseStock, ["@=elcodi_config('product.use_stock', false)"]]

    #
    # Factory for Variant entities
    #
    elcodi.factory.product_variant:
        class: %elcodi.factory.product_variant.class%
        parent: elcodi.factory.abstract.purchasable
        calls:
            - [setEntityNamespace, ["%elcodi.entity.product_variant.class%"]]

    #
    # Factory for Manufacturer entities
    #
    elcodi.factory.manufacturer:
        class: %elcodi.factory.manufacturer.class%
        calls:
            - [setEntityNamespace, ["%elcodi.entity.manufacturer.class%"]]

    #
    # Factory for Category entities
    #
    elcodi.factory.category:
        class: %elcodi.factory.category.class%
        calls:
            - [setEntityNamespace, ["%elcodi.entity.category.class%"]]
