services:

    #
    # Form Types
    #
    elcodi.core.product.form_type.category:
        class: %elcodi.core.product.form_type.category.class%
        tags:
            - { name: form.type, alias: elcodi_core_form_types_category }

    elcodi.core.product.form_type.manufacturer:
        class: %elcodi.core.product.form_type.manufacturer.class%
        tags:
            - { name: form.type, alias: elcodi_core_form_types_manufacturer }

    elcodi.core.product.form_type.product:
        class: %elcodi.core.product.form_type.product.class%
        tags:
            - { name: form.type, alias: elcodi_core_form_types_product }
