services:

    #
    # Object Managers
    #
    elcodi.object_manager.product:
        class: Doctrine\Common\Persistence\ObjectManager
        factory_service: elcodi.manager_provider
        factory_method: getManagerByEntityNamespace
        arguments:
            entity_namespace: %elcodi.core.product.entity.product.class%

    elcodi.object_manager.product_variant:
        class: Doctrine\Common\Persistence\ObjectManager
        factory_service: elcodi.manager_provider
        factory_method: getManagerByEntityNamespace
        arguments:
            entity_namespace: %elcodi.core.product.entity.product_variant.class%

    elcodi.object_manager.category:
        class: Doctrine\Common\Persistence\ObjectManager
        factory_service: elcodi.manager_provider
        factory_method: getManagerByEntityNamespace
        arguments:
            entity_namespace: %elcodi.core.product.entity.category.class%

    elcodi.object_manager.manufacturer:
        class: Doctrine\Common\Persistence\ObjectManager
        factory_service: elcodi.manager_provider
        factory_method: getManagerByEntityNamespace
        arguments:
            entity_namespace: %elcodi.core.product.entity.manufacturer.class%
