services:

    #
    # Object Managers
    #
    elcodi.object_manager.product:
        parent: elcodi.abstract_manager
        arguments: [ %elcodi.core.product.entity.product.class% ]

    elcodi.object_manager.product_variant:
        parent: elcodi.abstract_manager
        arguments: [ %elcodi.core.product.entity.product_variant.class% ]

    elcodi.object_manager.category:
        parent: elcodi.abstract_manager
        arguments: [ %elcodi.core.product.entity.category.class% ]

    elcodi.object_manager.manufacturer:
        parent: elcodi.abstract_manager
        arguments: [ %elcodi.core.product.entity.manufacturer.class% ]
