services:

    #
    # Services
    #
    elcodi.core.product.service.category_manager:
        class: %elcodi.core.product.service.category_manager.class%
        parent: elcodi.core.core.service.abstract_cache_wrapper
        calls:
            - [setKey, [%elcodi.core.product.menu_cache_key%]]
            - [setLoadOnlyCategoriesWithProducts, [%elcodi.core.product.load_only_categories_with_products%]]
            - [load]

    elcodi.core.product.service.product_collection_provider:
        class: %elcodi.core.product.service.product_collection_provider.class%
        arguments:
            product_repository: @elcodi.core.product.repository.product
            locale: %locale%
