services:

    #
    # Services
    #
    elcodi.provider.category_tree:
        class: %elcodi.provider.category_tree.class%
        arguments:
            - @elcodi.repository.category

    elcodi.provider.product_collection:
        class: %elcodi.provider.product_collection.class%
        arguments:
            - @elcodi.repository.product
            - "@=elcodi_config('product.use_stock', false)"
