services:

    #
    # Services
    #
    elcodi.provider.category_tree:
        class: %elcodi.provider.category_tree.class%
        arguments:
            category_repository: @elcodi.repository.category

    elcodi.provider.product_collection:
        class: %elcodi.provider.product_collection.class%
        arguments:
            product_repository: @elcodi.repository.product
