services:

    #
    # Twig extensions
    #
    elcodi.twig_extension.product:
        class: %elcodi.twig_extension.product.class%
        arguments: ~
        tags:
            - { name: twig.extension }
