services:

    #
    # Twig extensions
    #
    elcodi.twig_extension.product:
        class: Elcodi\Component\Product\Twig\ProductExtension
        arguments: ~
        tags:
            - { name: twig.extension }
